version: '3.8'
services:
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  configserver:
    build: ./configServer
    container_name: configserver
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

  userservice:
    build: ./userService
    container_name: userservice
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

  activityservice:
    build: ./activityService
    container_name: activityservice
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

  aiservice:
    build: ./aiService
    container_name: aiservice
    depends_on:
      - eureka
      - configserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
