services:
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - metafit-network
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8761 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  configserver:
    build: ./configServer
    container_name: configserver
    ports:
      - "8888:8888"
    depends_on:
      eureka:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - metafit-network
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8888 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - metafit-network
    env_file: .env
    restart: on-failure

  userservice:
    build: ./userService
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - metafit-network
    env_file: .env
    restart: on-failure

  activityservice:
    build: ./activityService
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - metafit-network
    env_file: .env
    restart: on-failure

  aiservice:
    build: ./aiService
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - metafit-network
    env_file: .env
    restart: on-failure

networks:
  metafit-network:
    external: true
