spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
    mongodb:
      uri: ${MONGO_AI_URI}
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: activity-processor-group-v2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.header: false
        spring.json.value.default.type: com.metaFitAi.aiService.model.Activity
        spring.json.trusted.packages: "*"
kafka:
  topic:
    name: activity-events-v2

groq:
  api:
    url: ${GROQ_URL}
    key: ${GROQ_KEY}
    model: llama-3.3-70b-versatile
    role: user

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: "metrics"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/