spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/metaFitAi/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"

        - id: activityService
          uri: lb://activityService
          predicates:
            - Path=/metaFitAi/activities/**
          filters:
            - JwtAuthentication
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@userKeyResolver}"

        - id: aiService
          uri: lb://aiService
          predicates:
            - Path=/metaFitAi/recommendations/**
          filters:
            - JwtAuthentication
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@userKeyResolver}"

jwt:
  secret: ${JWT_SECRET:5367566B5970337336763979244226452948404D6351665468576D5A71347437}

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}